"use client";
import { useEffect,useState } from "react";
import { useAuthStore } from "@/stores/auth-store";
type Setting={key:string;label:string;type:"NUMBER"|"BOOLEAN";value:string;minimum:number;maximum:number;description:string};
const headers=()=>{const token=useAuthStore.getState().token||localStorage.getItem("edrms_access_token");return {"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})};};
export default function ApplicationSettings(){
  const [settings,setSettings]=useState<Setting[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);fetch("/api/admin/config/application",{headers:headers(),signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.message||"Unable to load settings");if(active)setSettings(data);}).catch(cause=>{if(active)setError(controller.signal.aborted?"Loading timed out. Reload this screen to try again.":cause.message);}).finally(()=>clearTimeout(timer));return()=>{active=false;controller.abort();clearTimeout(timer);};},[]);
  const save=async(setting:Setting)=>{setBusy(true);setError("");setMessage("");try{const response=await fetch(`/api/admin/config/application/${setting.key}`,{method:"PUT",headers:headers(),body:JSON.stringify({value:setting.value}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(data.message||"Unable to save setting");setMessage("Saved. This recovery period applies to future deletions.");}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save");}finally{setBusy(false);}};
  return <section className="flex-1 min-h-0 overflow-auto"><div className="max-w-3xl space-y-4"><div><h2 className="text-lg font-semibold">Application Configuration</h2><p className="text-sm text-slate-500 mt-1">Manage application-wide settings. Each setting has a defined type and validation.</p></div>{error&&<p role="alert" className="rounded-xl bg-rose-50 text-rose-700 p-4 text-sm">{error}</p>}{message&&<p role="status" className="rounded-xl bg-green-50 text-green-700 p-4 text-sm">{message}</p>}{settings.map(setting=><form key={setting.key} onSubmit={event=>{event.preventDefault();void save(setting);}} className="border rounded-xl bg-white p-5 space-y-3"><label className="block font-semibold text-sm" htmlFor={setting.key}>{setting.label}</label><p className="text-sm text-slate-500">{setting.description}</p><div className="flex flex-wrap gap-3 items-center">{setting.type==="BOOLEAN"?<select id={setting.key} disabled={busy} value={setting.value} onChange={event=>setSettings(values=>values.map(value=>value.key===setting.key?{...value,value:event.target.value}:value))} className="border rounded-lg px-3 py-2"><option value="true">Enabled</option><option value="false">Disabled</option></select>:<input id={setting.key} disabled={busy} required type="number" step="1" min={setting.minimum} max={setting.maximum} value={setting.value} onChange={event=>setSettings(values=>values.map(value=>value.key===setting.key?{...value,value:event.target.value}:value))} className="border rounded-lg px-3 py-2 w-36"/>}<button type="submit" disabled={busy} className="rounded-lg bg-orange-500 text-white px-4 py-2 text-sm disabled:opacity-50">{busy?"Saving…":"Save setting"}</button></div><p className="text-xs text-slate-500">Deleted documents remain recoverable until their deadline. Expired files are cleaned up automatically while the backend is running.</p></form>)}</div></section>;
}
