"use client";
import { useEffect, useState } from "react";
import { useAuthStore } from "@/stores/auth-store";
import { useDocumentStore } from "@/stores/document-store";
import { X, Hash } from "lucide-react";
type Config = {prefix:string;dateMode:string;padding:number;nextNumber:number;revision:number;preview:string};
const headers=()=>{const token=useAuthStore.getState().token || localStorage.getItem("edrms_access_token"); return {"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})};};
async function readResponse(response:Response) {const data=await response.json(); if(!response.ok) throw new Error(data.message || "Unable to load folder numbering"); return data as Config;}
export function NumberingPreview({folderId}:{folderId:string|null}) {
  const [config,setConfig]=useState<Config|null>(null),[error,setError]=useState("");
  useEffect(()=>{setConfig(null);setError("");if(!folderId)return; let active=true;const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),15000);
    fetch(`/api/folders/${folderId}/numbering`,{headers:headers(),signal:controller.signal}).then(readResponse).then(value=>{if(active)setConfig(value);}).catch(()=>{if(active)setError("Numbering preview unavailable. The document ID will be assigned when saved.");}).finally(()=>clearTimeout(timer));
    return()=>{active=false;clearTimeout(timer);controller.abort();};},[folderId]);
  if(!folderId)return null;
  return <div className="rounded-lg border bg-slate-50 p-3 text-xs mb-4"><span className="font-medium">Document ID: </span>{config?<><strong className="break-all text-orange-700">{config.preview}</strong><p className="mt-1 text-slate-500">Preview only. The next available number is assigned when saved; the original filename is kept.</p></>:error || "Loading next document ID…"}</div>;
}
export default function FolderNumbering({initialFolderId,onClose}:{initialFolderId:string|null;onClose:()=>void}) {
  const {folders}=useDocumentStore(); const {user}=useAuthStore();
  const allowed=folders.filter(f=>user?.role==="SUPER_ADMIN" || !user?.assignedFolderIds?.length || user.assignedFolderIds.includes(f.id));
  const [folderId,setFolderId]=useState(initialFolderId || allowed[0]?.id || "");
  const [config,setConfig]=useState<Config|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
  useEffect(()=>{setConfig(null);setError("");setMessage("");if(!folderId)return;let active=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
    fetch(`/api/folders/${folderId}/numbering`,{headers:headers(),signal:controller.signal}).then(readResponse).then(value=>{if(active)setConfig(value);}).catch(cause=>{if(active)setError(controller.signal.aborted?"Loading timed out. Try Reload.":cause.message);}).finally(()=>clearTimeout(timer));
    return()=>{active=false;clearTimeout(timer);controller.abort();};},[folderId,reload]);
  const path=(id:string)=>{const pieces:string[]=[];const seen=new Set<string>();let node=folders.find(f=>f.id===id);while(node&&!seen.has(node.id)){seen.add(node.id);pieces.unshift(node.name);node=folders.find(f=>f.id===node!.parentId);}return pieces.join(" / ");};
  const preview=()=>{if(!config)return "";const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const date=(name:string)=>parts.find(p=>p.type===name)?.value || "";const count={NONE:0,YEAR:1,YEAR_MONTH:2,YEAR_MONTH_DAY:3}[config.dateMode] || 0;return [config.prefix,...[date("year"),date("month"),date("day")].slice(0,count),String(config.nextNumber).padStart(config.padding,"0")].join("-");};
  const save=async()=>{if(!config)return;setBusy(true);setError("");setMessage("");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const saved=await readResponse(await fetch(`/api/folders/${folderId}/numbering`,{method:"PUT",headers:headers(),body:JSON.stringify(config),signal:controller.signal}));setConfig(saved);setMessage("Saved. New uploads will use this format.");}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save");}finally{clearTimeout(timer);setBusy(false);}};
  const input="w-full border rounded-lg px-3 py-2 text-sm mt-1 bg-white";
  return <div className="fixed inset-0 z-50 bg-slate-900/50 flex items-center justify-center p-3"><section role="dialog" aria-modal="true" aria-label="Folder numbering" className="bg-white rounded-2xl w-full max-w-2xl max-h-[95dvh] flex flex-col shadow-xl"><header className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold flex items-center gap-2"><Hash size={19}/>Folder numbering</h2><p className="text-xs text-slate-500 mt-1">Set document IDs for new uploads in each folder.</p></div><button disabled={busy} aria-label="Close folder numbering" onClick={onClose} className="p-2"><X size={20}/></button></header><div className="p-5 overflow-y-auto space-y-4">
    <label className="block text-sm font-medium">Folder<select className={input} value={folderId} disabled={busy} onChange={e=>setFolderId(e.target.value)}>{allowed.map(f=><option key={f.id} value={f.id}>{path(f.id)}</option>)}</select></label>
    {error&&<p role="alert" className="bg-rose-50 p-3 text-sm text-rose-700 rounded-lg">{error}</p>}{message&&<p role="status" className="text-sm text-green-700">{message}</p>}
    {config?<><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="text-sm font-medium">Prefix<input className={input} maxLength={40} value={config.prefix} onChange={e=>setConfig({...config,prefix:e.target.value.toUpperCase()})}/><span className="text-xs text-slate-500">Letters and numbers, e.g. MEDDOCS or ADMDOCS</span></label><label className="text-sm font-medium">Date format<select className={input} value={config.dateMode} onChange={e=>setConfig({...config,dateMode:e.target.value})}><option value="NONE">No date</option><option value="YEAR">Year</option><option value="YEAR_MONTH">Year – Month</option><option value="YEAR_MONTH_DAY">Year – Month – Day</option></select></label><label className="text-sm font-medium">Next sequence number<input className={input} type="number" min={1} max={9000000000000000} step={1} value={config.nextNumber} onChange={e=>setConfig({...config,nextNumber:Number(e.target.value)})}/></label><label className="text-sm font-medium">Minimum sequence digits<select className={input} value={config.padding} onChange={e=>setConfig({...config,padding:Number(e.target.value)})}>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label></div>
    <div className="rounded-xl bg-orange-50 border border-orange-100 p-4"><p className="text-xs text-orange-700">Example next document ID</p><p className="font-semibold text-lg break-all mt-1">{preview()}</p></div><p className="text-xs text-slate-500 leading-relaxed">Sequence is always included and never resets on a new day or year. You can move the next number forward. Prefixes are reserved to one folder, including previously used prefixes. Existing IDs and filenames stay unchanged. Dates use India time. Preview numbers can change when another upload is saved.</p></>:!error&&<p className="text-sm text-slate-500">{folderId?"Loading configuration…":"Create a folder to configure numbering."}</p>}
    </div><footer className="border-t p-4 flex gap-3 justify-end"><button disabled={busy} onClick={()=>setReload(v=>v+1)} className="border rounded-lg px-4 py-2 text-sm">Reload</button><button disabled={busy||!config} onClick={()=>void save()} className="bg-orange-500 text-white rounded-lg px-4 py-2 text-sm disabled:opacity-40">{busy?"Saving…":"Save configuration"}</button></footer></section></div>;
}
